package java_encrypt;

/**
 * created by:      Tony Ranieri
 * creation date:   Oct 2015
 */

import java.util.*;

public class dict {
    
    /** dictionary, input is char and output is int **/
    public static int DICTINT(char letter)	{
		
	Map<Character, Integer> dictionary = new HashMap<Character, Integer>();
	dictionary.put('0', 0);
	dictionary.put('1', 1);
	dictionary.put('2', 2);
	dictionary.put('3', 3);
	dictionary.put('4', 4);
	dictionary.put('5', 5);
	dictionary.put('6', 6);
	dictionary.put('7', 7);
	dictionary.put('8', 8);
	dictionary.put('9', 9);
	dictionary.put('A', 10);
	dictionary.put('B', 11);
	dictionary.put('C', 12);
	dictionary.put('D', 13);
	dictionary.put('E', 14);
	dictionary.put('F', 15);
	dictionary.put('G', 16);
	dictionary.put('H', 17);
	dictionary.put('I', 18);
	dictionary.put('J', 19);
	dictionary.put('K', 20);
	dictionary.put('L', 21);
	dictionary.put('M', 22);
	dictionary.put('N', 23);
	dictionary.put('O', 24);
	dictionary.put('P', 25);
	dictionary.put('Q', 26);
	dictionary.put('R', 27);
	dictionary.put('S', 28);
	dictionary.put('T', 29);
	dictionary.put('U', 30);
	dictionary.put('V', 31);
	dictionary.put('W', 32);
	dictionary.put('X', 33);
	dictionary.put('Y', 34);
	dictionary.put('Z', 35);
	dictionary.put('a', 36);
	dictionary.put('b', 37);
	dictionary.put('c', 38);
	dictionary.put('d', 39);
	dictionary.put('e', 40);
	dictionary.put('f', 41);
	dictionary.put('g', 42);
	dictionary.put('h', 43);
	dictionary.put('i', 44);
	dictionary.put('j', 45);
	dictionary.put('k', 46);
	dictionary.put('l', 47);
	dictionary.put('m', 48);
	dictionary.put('n', 49);
	dictionary.put('o', 50);
	dictionary.put('p', 51);
	dictionary.put('q', 52);
	dictionary.put('r', 53);
	dictionary.put('s', 54);
	dictionary.put('t', 55);
	dictionary.put('u', 56);
	dictionary.put('v', 57);
	dictionary.put('w', 58);
	dictionary.put('x', 59);
	dictionary.put('y', 60);
	dictionary.put('z', 61);
	dictionary.put(' ', 62);
	dictionary.put('.', 63);
	dictionary.put('?', 64);
	dictionary.put('!', 65);
	dictionary.put('@', 66);
	dictionary.put('#', 67);
	dictionary.put('$', 68);
	dictionary.put('%', 69);
	dictionary.put('^', 70);
	dictionary.put('&', 71);
	dictionary.put('*', 72);
	dictionary.put('(', 73);
	dictionary.put(')', 74);
	dictionary.put('-', 75);
	dictionary.put('=', 76);
	dictionary.put('+', 77);
	dictionary.put(';', 78);
	dictionary.put(':', 79);
	dictionary.put('<', 80);
	dictionary.put('>', 81);
	dictionary.put('\'', 82);
	dictionary.put('\"', 83);
	dictionary.put('_', 84);
	dictionary.put('\\', 85);
	dictionary.put('[', 86);
	dictionary.put(']', 87);
	dictionary.put('{', 88);
	dictionary.put('}', 89);
	dictionary.put('/', 90);
	dictionary.put('`', 91);
	dictionary.put('~', 92);
	dictionary.put('\n', 93);
	dictionary.put('|', 94);
	dictionary.put('|', 95);
	dictionary.put('|', 96);
	dictionary.put('|', 97);
	dictionary.put('|', 98);
	dictionary.put('|', 99);
	return (dictionary.get(letter));
	}
		
    /** dictionary, input is int and output is char **/
    public static char DICTCHAR(int num)	{
		
	Map<Integer, Character> dictionary = new HashMap<Integer, Character>();
	dictionary.put(1, '1');
	dictionary.put(2, '2');
	dictionary.put(3, '3');
	dictionary.put(4, '4');
	dictionary.put(5, '5');
	dictionary.put(6, '6');
	dictionary.put(7, '7');
	dictionary.put(8, '8');
	dictionary.put(9, '9');
	dictionary.put(0, '0');
	dictionary.put(10, 'A');
	dictionary.put(11, 'B');
	dictionary.put(12, 'C');
	dictionary.put(13, 'D');
	dictionary.put(14, 'E');
	dictionary.put(15, 'F');
	dictionary.put(16, 'G');
	dictionary.put(17, 'H');
	dictionary.put(18, 'I');
	dictionary.put(19, 'J');
	dictionary.put(20, 'K');
	dictionary.put(21, 'L');
	dictionary.put(22, 'M');
	dictionary.put(23, 'N');
	dictionary.put(24, 'O');
	dictionary.put(25, 'P');
	dictionary.put(26, 'Q');
	dictionary.put(27, 'R');
	dictionary.put(28, 'S');
	dictionary.put(29, 'T');
	dictionary.put(30, 'U');
	dictionary.put(31, 'V');
	dictionary.put(32, 'W');
	dictionary.put(33, 'X');
	dictionary.put(34, 'Y');
	dictionary.put(35, 'Z');
	dictionary.put(36, 'a');
	dictionary.put(37, 'b');
	dictionary.put(38, 'c');
	dictionary.put(39, 'd');
	dictionary.put(40, 'e');
	dictionary.put(41, 'f');
	dictionary.put(42, 'g');
	dictionary.put(43, 'h');
	dictionary.put(44, 'i');
	dictionary.put(45, 'j');
	dictionary.put(46, 'k');
	dictionary.put(47, 'l');
	dictionary.put(48, 'm');
	dictionary.put(49, 'n');
	dictionary.put(50, 'o');
	dictionary.put(51, 'p');
	dictionary.put(52, 'q');
	dictionary.put(53, 'r');
	dictionary.put(54, 's');
	dictionary.put(55, 't');
	dictionary.put(56, 'u');
	dictionary.put(57, 'v');
	dictionary.put(58, 'w');
	dictionary.put(59, 'x');
	dictionary.put(60, 'y');
	dictionary.put(61, 'z');
	dictionary.put(62, ' ');
	dictionary.put(63, '.');
	dictionary.put(64, '?');
	dictionary.put(65, '!');
	dictionary.put(66, '@');
	dictionary.put(67, '#');
	dictionary.put(68, '$');
	dictionary.put(69, '%');
	dictionary.put(70, '^');
	dictionary.put(71, '&');
	dictionary.put(72, '*');
	dictionary.put(73, '(');
	dictionary.put(74, ')');
	dictionary.put(75, '-');
	dictionary.put(76, '=');
	dictionary.put(77, '+');
	dictionary.put(78, ';');
	dictionary.put(79, ':');
	dictionary.put(80, '<');
	dictionary.put(81, '>');
	dictionary.put(82, '\'');
	dictionary.put(83, '\"');
	dictionary.put(84, '_');
	dictionary.put(85, '\\');
	dictionary.put(86, '[');
	dictionary.put(87, ']');
	dictionary.put(88, '{');
	dictionary.put(89, '}');
	dictionary.put(90, '/');
	dictionary.put(91, '`');
	dictionary.put(92, '~');
	dictionary.put(93, '\n');
	dictionary.put(94, '|');
	dictionary.put(95, '|');
	dictionary.put(96, '|');
	dictionary.put(97, '|');
	dictionary.put(98, '|');
	dictionary.put(99, '|');
	return (dictionary.get(num));
	}
}
